#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Legacy Codex integration: older versions of this script hand-wrote
# ~/.agents/plugins/waypoint.json, which current codex CLIs pick up as a
# SECOND 'waypoint-plugins' marketplace — shadowing the CLI-registered one.
# Unlike ptek-jira-cli's shared marketplace.json, this file was wholly
# generated by this script (dedicated filename, waypoint entries only), so
# migration is a straight delete — no entry pruning needed.
LEGACY_CODEX_MARKETPLACE="$HOME/.agents/plugins/waypoint.json"
remove_legacy_codex_marketplace() {
  [ -f "$LEGACY_CODEX_MARKETPLACE" ] || return 0
  if ! rm "$LEGACY_CODEX_MARKETPLACE"; then
    echo "  Warning: could not remove legacy $LEGACY_CODEX_MARKETPLACE — check permissions"
    echo "           Until removed it may shadow the fresh 'waypoint-plugins' registration."
    return 1
  fi
  echo "  Removed legacy $LEGACY_CODEX_MARKETPLACE"
}

# Ensure plugin_hooks feature flag is enabled in ~/.codex/config.toml
# (waypoint's hooks need it; not reverted on uninstall — other plugins may use it)
# All matching and editing is scoped to the [features] table — a plugin_hooks
# key in any other table belongs to someone else and must not be touched.
ensure_codex_plugin_hooks() {
  CODEX_CONFIG="$HOME/.codex/config.toml"
  if [ ! -f "$CODEX_CONFIG" ]; then
    echo "  ~/.codex/config.toml not found — add manually: [features] plugin_hooks = true"
    return 0
  fi
  # Single source of truth for the header match. TOML allows the same table
  # to be spelled with leading whitespace, whitespace inside the brackets,
  # and a bare or quoted key: [features], [ features ], ["features"], etc.
  # Shared with awk via ENVIRON — 'awk -v' would mangle the backslashes.
  # shellcheck disable=SC2089,SC2090  # the quotes are regex characters (data), not shell quoting
  FEATURES_HEADER_RE='^[[:space:]]*\[[[:space:]]*["'\'']?features["'\'']?[[:space:]]*\]'
  # shellcheck disable=SC2090  # same rationale — exported as data for awk's ENVIRON
  export FEATURES_HEADER_RE
  FEATURES_HOOKS_LINE="$(awk '
    BEGIN { re = ENVIRON["FEATURES_HEADER_RE"] }
    /^[[:space:]]*\[/ { in_features = ($0 ~ re) }
    in_features && /^[[:space:]]*plugin_hooks[[:space:]]*=/ { print; exit }
  ' "$CODEX_CONFIG")"
  if printf '%s' "$FEATURES_HOOKS_LINE" | grep -qE "=[[:space:]]*true[[:space:]]*$"; then
    echo "  plugin_hooks already enabled in config.toml"
  elif [ -n "$FEATURES_HOOKS_LINE" ]; then
    # Present in [features] but not true — update in place, within the table only
    awk '
      BEGIN { re = ENVIRON["FEATURES_HEADER_RE"] }
      /^[[:space:]]*\[/ { in_features = ($0 ~ re) }
      in_features && /^[[:space:]]*plugin_hooks[[:space:]]*=/ { sub(/=.*/, "= true") }
      { print }
    ' "$CODEX_CONFIG" > "${CODEX_CONFIG}.tmp" \
      && mv "${CODEX_CONFIG}.tmp" "$CODEX_CONFIG"
    echo "  Updated plugin_hooks to true in config.toml"
  elif grep -qE "$FEATURES_HEADER_RE" "$CODEX_CONFIG"; then
    awk '
      BEGIN { re = ENVIRON["FEATURES_HEADER_RE"] }
      $0 ~ re { print; print "plugin_hooks = true"; next }
      { print }
    ' "$CODEX_CONFIG" > "${CODEX_CONFIG}.tmp" \
      && mv "${CODEX_CONFIG}.tmp" "$CODEX_CONFIG"
    echo "  Added plugin_hooks = true under [features] in config.toml"
  else
    printf '\n[features]\nplugin_hooks = true\n' >> "$CODEX_CONFIG"
    echo "  Added [features] + plugin_hooks = true to config.toml"
  fi
}

main() {
UNINSTALL=false
RELOAD=false
case "${1:-}" in
  --uninstall) UNINSTALL=true ;;
  --reload) RELOAD=true ;;
  "") ;;
  *)
    echo "Usage: $0 [--reload|--uninstall]" >&2
    return 1
    ;;
esac
if [ "$#" -gt 1 ]; then
  echo "Usage: $0 [--reload|--uninstall]" >&2
  return 1
fi

if $UNINSTALL; then
  echo "Waypoint Plugin Uninstall"
  echo "========================="
  echo ""
  UNINSTALL_OK=true

  # --- Claude Code ---
  # Plugin removal is attempted unconditionally, not gated on marketplace
  # registration being present — cache/config state can diverge from the
  # marketplace registration (partial failure, manual edits), so a plugin
  # can be left installed even when 'plugin marketplace list' finds nothing.
  # Detect claude binary only — 'cc' collides with the system C compiler.
  if CLAUDE_CMD=$(command -v claude 2>/dev/null); then
    # Scoped-only: an unscoped 'claude plugin uninstall waypoint' could match
    # a same-named plugin from a different marketplace and delete something
    # this script does not own. Applies to every install/uninstall call here.
    CLAUDE_UNINSTALL_OUTPUT=$("$CLAUDE_CMD" plugin uninstall "waypoint@waypoint-plugins" 2>&1) && CLAUDE_UNINSTALL_RC=0 || CLAUDE_UNINSTALL_RC=$?
    if [ "$CLAUDE_UNINSTALL_RC" -eq 0 ]; then
      echo "Removed Claude Code plugin"
    elif echo "$CLAUDE_UNINSTALL_OUTPUT" | grep -qi "not found in installed plugins"; then
      echo "Claude Code: plugin was not installed"
    else
      echo "Warning: failed to uninstall Claude Code plugin — $CLAUDE_UNINSTALL_OUTPUT"
      UNINSTALL_OK=false
    fi

    if ! CLAUDE_MARKETPLACES=$("$CLAUDE_CMD" plugin marketplace list 2>/dev/null); then
      echo "Warning: could not query Claude Code marketplaces — remove manually if registered:"
      echo "    claude plugin marketplace remove waypoint-plugins"
      UNINSTALL_OK=false
    # Anchored so a name like 'waypoint-plugins-old' doesn't false-positive.
    elif echo "$CLAUDE_MARKETPLACES" | grep -qE "(^|[[:space:]])waypoint-plugins$"; then
      if "$CLAUDE_CMD" plugin marketplace remove waypoint-plugins 2>/dev/null; then
        echo "Removed Claude Code marketplace registration"
      else
        echo "Warning: failed to remove Claude Code marketplace registration — remove manually:"
        echo "    claude plugin marketplace remove waypoint-plugins"
        UNINSTALL_OK=false
      fi
    else
      echo "Claude Code: no marketplace registration found"
    fi
  fi

  # --- Codex ---
  # Same unconditional-removal rationale as the Claude block above. Verified
  # in ptek-jira-cli: 'codex plugin remove' is idempotent (exits 0 even when
  # the plugin was never installed), so a nonzero exit is a genuine failure.
  if command -v codex &>/dev/null; then
    if codex plugin remove "waypoint@waypoint-plugins" 2>/dev/null; then
      echo "Removed Codex plugin"
    else
      echo "Warning: failed to remove Codex plugin — remove manually:"
      echo "    codex plugin remove waypoint@waypoint-plugins"
      UNINSTALL_OK=false
    fi

    if ! CODEX_MARKETPLACES=$(codex plugin marketplace list 2>/dev/null); then
      echo "Warning: could not query Codex marketplaces — remove manually if registered:"
      echo "    codex plugin marketplace remove waypoint-plugins"
      UNINSTALL_OK=false
    elif echo "$CODEX_MARKETPLACES" | grep -qE "(^|[[:space:]])waypoint-plugins([[:space:]]|$)"; then
      if codex plugin marketplace remove waypoint-plugins 2>/dev/null; then
        echo "Removed Codex marketplace registration"
      else
        echo "Warning: failed to remove Codex marketplace registration — remove manually:"
        echo "    codex plugin marketplace remove waypoint-plugins"
        UNINSTALL_OK=false
      fi
    else
      echo "Codex: no marketplace registration found"
    fi
  fi

  remove_legacy_codex_marketplace || UNINSTALL_OK=false
  # plugin_hooks not reverted — it's a feature flag that may be used by other plugins

  echo ""
  if $UNINSTALL_OK; then
    echo "Done. Restart sessions to apply."
    return 0
  fi
  echo "Done (with failures — review output above)."
  return 1
fi

if $RELOAD; then
  echo "Dev reload: waypoint@waypoint-plugins"
  echo ""
  RELOAD_OK=true

  # --- Claude Code ---
  if CLAUDE_CMD=$(command -v claude 2>/dev/null); then
    echo "Claude Code: uninstalling waypoint..."
    # Scoped-only, same rationale as the --uninstall path above.
    RELOAD_UNINSTALL_OUTPUT=$("$CLAUDE_CMD" plugin uninstall "waypoint@waypoint-plugins" 2>&1) && RELOAD_UNINSTALL_RC=0 || RELOAD_UNINSTALL_RC=$?
    if [ "$RELOAD_UNINSTALL_RC" -ne 0 ] && ! echo "$RELOAD_UNINSTALL_OUTPUT" | grep -qi "not found in installed plugins"; then
      echo "  ✘ failed to uninstall waypoint before reload — $RELOAD_UNINSTALL_OUTPUT"
      RELOAD_OK=false
    fi
    echo "Claude Code: reinstalling waypoint..."
    if "$CLAUDE_CMD" plugin install "waypoint@waypoint-plugins" 2>/dev/null; then
      echo "  ✔ waypoint reloaded"
    else
      echo "  ✘ waypoint reinstall failed — waypoint is now UNINSTALLED (reload removes before reinstalling)."
      echo "    Restore it with: claude plugin install waypoint@waypoint-plugins   (or rerun ./setup-plugins.sh)"
      RELOAD_OK=false
    fi
  else
    echo "Claude Code: not found, skipping"
  fi

  echo ""

  # --- Codex ---
  # 'codex plugin add' on an installed plugin re-syncs the cache in place
  # (same-version content changes included) — no remove/reinstall needed.
  if command -v codex &>/dev/null; then
    echo "Codex: reinstalling waypoint..."
    if codex plugin add "waypoint@waypoint-plugins"; then
      echo "  ✔ waypoint reloaded"
    else
      echo "  ✘ codex plugin add failed — is the waypoint-plugins marketplace registered? (run $0)"
      RELOAD_OK=false
    fi
  else
    echo "Codex: not found, skipping"
  fi

  echo ""
  if $RELOAD_OK; then
    echo "Done. Start a new session to pick up updated hooks and skill instructions."
    return 0
  fi
  echo "Done (with failures — review output above)."
  return 1
fi

echo "Waypoint Plugin Setup"
echo "====================="
echo ""
echo "Repo: $REPO_DIR"
echo ""
SETUP_OK=true

# --- Claude Code ---
if CLAUDE_CMD=$(command -v claude 2>/dev/null); then
  echo "Claude Code detected ($CLAUDE_CMD)"

  # Anchored so a name like 'waypoint-plugins-old' doesn't false-positive
  # into the update branch below.
  if "$CLAUDE_CMD" plugin marketplace list 2>/dev/null | grep -qE "(^|[[:space:]])waypoint-plugins$"; then
    if ! "$CLAUDE_CMD" plugin marketplace update waypoint-plugins 2>/dev/null; then
      echo "  Update failed (stale path?). Re-registering..."
      "$CLAUDE_CMD" plugin marketplace remove waypoint-plugins 2>/dev/null || true
      "$CLAUDE_CMD" plugin marketplace add "$REPO_DIR" \
        || { echo "  Warning: marketplace re-registration failed — Claude setup incomplete"; SETUP_OK=false; }
    else
      echo "  Updated marketplace registration"
    fi
  else
    echo "  Registering marketplace..."
    "$CLAUDE_CMD" plugin marketplace add "$REPO_DIR" \
      || { echo "  Warning: marketplace registration failed — Claude setup incomplete"; SETUP_OK=false; }
  fi

  echo ""
  if $SETUP_OK; then
    echo "  Installing waypoint plugin..."
    "$CLAUDE_CMD" plugin install "waypoint@waypoint-plugins" 2>/dev/null \
      || { echo "  (install manually: claude plugin install waypoint@waypoint-plugins)"; SETUP_OK=false; }
  else
    echo "  Skipping plugin install — marketplace registration failed"
  fi
  echo ""
else
  echo "Claude Code not found — skipping."
  echo ""
fi

# --- Codex ---
if command -v codex &>/dev/null; then
  echo "Codex detected"

  # Idempotent: exits 0 and reports the root if already registered
  if codex plugin marketplace add "$REPO_DIR"; then
    # Remove the legacy hand-written marketplace file only after the CLI
    # registration exists, so a failed registration never strips the file
    # a user still depends on
    if remove_legacy_codex_marketplace; then
      echo ""
      echo "  Installing waypoint plugin..."
      # 'add' also upgrades/re-syncs an already-installed plugin in place
      codex plugin add "waypoint@waypoint-plugins" \
        || { echo "  (install manually: codex plugin add waypoint@waypoint-plugins)"; SETUP_OK=false; }
    else
      # A lingering legacy marketplace can shadow the fresh registration —
      # installing now could pull stale content
      echo "  Skipping plugin install until legacy cleanup succeeds"
      SETUP_OK=false
    fi

    ensure_codex_plugin_hooks
    echo ""
  else
    echo "  Warning: marketplace registration failed — Codex setup incomplete"
    echo "           (if 'codex plugin marketplace' is an unknown command, upgrade the codex CLI)"
    SETUP_OK=false
  fi
else
  echo "Codex not found — skipping."
  echo ""
fi

if $SETUP_OK; then
  echo "Done. Restart Claude Code / Codex sessions to activate hooks."
else
  echo "Done (with warnings — review output above)."
  return 1
fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
